language: node_js
node_js:
  - "stable"
services:
  - mongodb
before_script:
  - sleep 15
script:
  - npm start&
  - node_modules/.bin/newman run test/recomendador.postman_collection.json
  - npm test
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_API_NAME